version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/my-java-app

permissions:
  - object: /home/ec2-user/my-java-app/scripts/*.sh
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 0755  # Ensure scripts have executable permissions (rwxr-xr-x)

phases:
  install:
    runtime-versions:
      java: openjdk11
    commands:
      - echo "Installing Maven and Java"
      - yum install -y maven java-11-openjdk-devel  # Adjust package name for OpenJDK 11
      - chown -R ec2-user:ec2-user /home/ec2-user/my-java-app  # Ensure ownership by ec2-user

  build:
    commands:
      - echo "Build started on $(date)"
      - mvn clean install -f /home/ec2-user/my-java-app/pom.xml  # Adjust pom.xml location if needed
      - echo "Build completed on $(date)"

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root  # Execute as root for installation

    - location: scripts/set_permissions.sh
      timeout: 300
      runas: ec2-user  # Execute as ec2-user after installation

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user  # Execute as ec2-user

    - command: chmod +x /home/ec2-user/my-java-app/scripts/start_server.sh
      runas: root  # Execute as root to change permissions

  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: ec2-user  # Execute as ec2-user

    - command: chmod +x /home/ec2-user/my-java-app/scripts/stop_server.sh
      runas: root  # Execute as root to change permissions
