version: 0.0
os: linux

files:
  - source: /
    destination: /home/ec2-user/my-java-app

permissions:
  - object: /home/ec2-user/my-java-app
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: "755"
    type:
      - directory
      - file

hooks:
  BeforeInstall:
    - location: install_dependencies.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: setup.sh
      timeout: 300
      runas: ec2-user
  ApplicationStop:
    - location: stop_server.sh
      timeout: 300
      runas: ec2-user
  ApplicationStart:
    - location: start_server.sh
      timeout: 300
      runas: ec2-user