phases:
  install:
    runtime-versions:
      java: openjdk-11
    commands:
      - echo "Installing Maven and Java"
      - yum install -y maven java-11-openjdk-devel

  build:
    commands:
      - echo "Build started on $(date)"
      - mvn clean install -f pom.xml
      - echo "Build completed on $(date)"

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: root

    - location: scripts/set_permissions.sh
      timeout: 300
      runas: ec2-user

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ec2-user
    - command: chmod +x /home/ec2-user/my-java-app/scripts/start_server.sh

  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 300
      runas: ec2-user
    - command: chmod +x /home/ec2-user/my-java-app/scripts/stop_server.sh
