version: 0.2

phases:
  install:
    commands:
      - mvn clean install -f pom.xml 
      - cd scripts  # Change directory to scripts folder
      - chmod +x *.sh
      - ./install_dependencies.sh  # Execute install_dependencies.sh script
  pre_build:
    commands:
      - cd scripts  # Change directory to scripts folder
      - chmod +x *.sh
      - ./setup.sh  # Execute setup.sh script
  build:
    commands:
      - cd scripts  # Change directory to scripts folder
      - # Additional build commands as needed, e.g., javac src/Main.java
  post_build:
    commands:
      - cd scripts  # Change directory to scripts folder
      - chmod +x *.sh
      - ./start_server.sh  # Execute start_server.sh script
      - ./stop_server.sh   # Execute stop_server.sh script after deployment

artifacts:
  files:
    - '**/*'
