version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
  pre_build:
    commands:
      - echo "Installing Maven and Java"
      - apt-get update
      - apt-get install -y maven openjdk-11-jdk
  build:
    commands:
      - echo Build started on `date`
      - mvn clean install -f pom.xml
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
