version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
      java: corretto11
    commands:
      - echo "Installing Maven and Java"
      - yum install -y maven java-11-amazon-corretto-devel

  build:
    commands:
      - echo Build started on `date`
      - mvn clean install -f pom.xml
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
